variable "rg-location" {} 
variable "rg-name"  {}
variable "customer-name" {}
variable "env" {}
variable "createdby" {}
variable "creationdate" {}
variable "aks-vm-size" {}
variable "aks-subnet-id" {}
variable "la-workspace-resource-id" {}
